name: Bug report
description: Report a reproducible problem in rcbridge
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce.

  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: v0.1.0 or commit SHA
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Windows version
      placeholder: Windows 11 23H2
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: RC hardware
      placeholder: RC-N1 (RC231)

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact command(s) used.
      placeholder: |
        1. rcbridge run --port COM5 --baud 115200 --config config.json
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / captures
      description: Paste relevant logs or attach `captures/*.bin` if useful.
